### PR TITLE
I have implemented Email/Password signup page (issue 19)

### PR DESCRIPTION
**Pull request by Slok9931**

### CODE REVIEW

**Comment by Shashankpantiitbhilai** [comment]
resolve conflict  in following files
frontend/src/App.jsx
frontend/src/index.css
frontend/tailwind.config.js

**Comment by Slok9931** [comment]
Conflicts have been resolved

**Comment by prasachin** [comment]
Conflicting files
frontend/src/App.jsx 
resolve these to be merged !

**Pull request closed without merging**
